### ISSUE TITLE
EYEBALL

### ISSUE THREAD

**Issue by kurnal-volt** [kurnal-volt/marker-io-feedback#14]
[![Screenshot_2021-09-22_03-37-45.png](https://mrkr.io/s/614aa5092c892f37f9c007d9/2)](https://mrkr.io/s/614aa5092c892f37f9c007d9/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Reported by:** Sal Mani (smoney002@live.com) - [Contact via Marker.io](https://app.marker.io/i/614aa5092c892f37f9c00802_f7f645614aa96eb2?comments=1)

**Source URL:** [https://dev-portal.volt.ai/incidents](https://dev-portal.volt.ai/incidents)

**Console:** [❌  2 errors ⚠️  2 warnings ℹ️  1 info 📃  35 logs ](https://app.marker.io/i/614aa5092c892f37f9c00802_f7f645614aa96eb2?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 93.0.4577.82</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 950</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by volt-ai-willjay** [comment]
not an issue
