### ISSUE TITLE
Temporary password confusion

### ISSUE THREAD

**Issue by kurnal-volt** [kurnal-volt/marker-io-feedback#22]
[![Screenshot_2021-09-29_16-11-15.png](https://mrkr.io/s/615490226f3c7a4cbcf18883/2)](https://mrkr.io/s/615490226f3c7a4cbcf18883/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Reported by:** Sal Mani (smoney002@live.com) - [Contact via Marker.io](https://app.marker.io/i/615490236f3c7a4cbcf18885_4d9144e0aa7e703b?comments=1)

**Issue resolved?** [Notify reporter via Marker.io](https://app.marker.io/i/615490236f3c7a4cbcf18885_4d9144e0aa7e703b?status=1)

**Source URL:** [https://dev-portal.volt.ai/auth/register?email=smoney002@live.com](https://dev-portal.volt.ai/auth/register?email=smoney002@live.com)

**Console:** [ℹ️  1 info ](https://app.marker.io/i/615490236f3c7a4cbcf18885_4d9144e0aa7e703b?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 93.0.4577.82</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 1007</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by volt-ai-willjay** [comment]
Hotfix: wording `Password` => `Temporary Password`
